# Detection settings
detection:
  face_confidence: 0.5
  pose_confidence: 0.5
  object_confidence: 0.3
  
# Tracking settings
tracking:
  smoothing_factor: 0.1  # Lower = smoother, higher = more responsive
  kalman_process_noise: 0.01
  kalman_measurement_noise: 0.1
  max_lost_frames: 30  # Frames before switching to object detection
  
# Reframing settings
reframing:
  default_aspect_ratio: [9, 16]  # [width, height]
  padding_ratio: 0.1  # Extra space around subject
  min_zoom: 0.5  # Minimum zoom level (1.0 = no zoom)
  max_zoom: 2.0  # Maximum zoom level
  lead_room: 0.0  # Offset subject from center (0-0.5)
  
# Video settings
video:
  output_quality: 95  # 0-100
  output_codec: "mp4v"
  preview_scale: 0.5  # Scale for preview window
  
# Object detection settings
objects:
  saliency_threshold: 0.5
  preferred_classes:  # YOLOv8 classes to prioritize
    - "person"
    - "dog"
    - "cat"
    - "bird"
    - "car"
    - "bicycle"
