# Detection settings
detection:
  face_confidence: 0.7  # Higher for better accuracy
  pose_confidence: 0.5
  object_confidence: 0.3
  
# Tracking settings
tracking:
  use_keyframes: true  # Use keyframe-based tracking
  confidence_threshold: 0.25  # Min confidence to add keyframe
  interpolation_method: "cubic"  # cubic or linear
  min_keyframe_distance: 5  # Min frames between keyframes
  max_lost_frames: 30  # Frames before switching to object detection
  
  # Legacy settings (for compatibility)
  smoothing_factor: 0.1
  kalman_process_noise: 0.01
  kalman_measurement_noise: 0.1
  
# Reframing settings
reframing:
  default_aspect_ratio: [9, 16]  # [width, height]
  x_axis_only: true  # Only adjust horizontal position
  lead_room: 0.1  # Offset subject from center (0-0.5)
  
  # Disabled settings (no zoom or vertical movement)
  padding_ratio: 0.0
  min_zoom: 1.0
  max_zoom: 1.0
  
# Scene detection
scene_detection:
  enabled: true
  threshold: 30.0  # Histogram difference threshold
  min_scene_length: 10  # Min frames between cuts
  use_adaptive: true  # Adaptive threshold
  
# Video settings
video:
  output_quality: 95  # 0-100
  output_codec: "mp4v"
  preview_scale: 0.5  # Scale for preview window
  
# Object detection settings
objects:
  saliency_threshold: 0.5
  preferred_classes:  # YOLOv8 classes to prioritize
    - "person"
    - "dog"
    - "cat"
    - "bird"
    - "car"
    - "bicycle"
    - "sports ball"
    - "skateboard"
